### ISSUE TITLE
Vector conversion

### ISSUE THREAD

**Issue by eizengan** [LaurentGomila/SFML.Net#104]
Currently the constructors used to convert between the various SFML.Window.Vector types are not present in the API. They should probably be added to the body of the class or as extension methods. Adding conversions to the System.Drawing.Size structs should be considered as well, since the conversion process would be relatively straightforward and this would tie SMFL to the built-in C# libraries in a sensible manner.

**Comment by zsbzsb** [comment]
>Currently the constructors used to convert between the various SFML.Window.Vector types are not present in the API.

Really?
https://github.com/LaurentGomila/SFML.Net/blob/master/src/System/Vector2.cs#L190

>Adding conversions to the System.Drawing.Size structs should be considered as well

It could be considered.

**Comment by eizengan** [comment]
If you guys are interested in conversion between the Vector structs and the built-in equivalents (Point, Size, etc.), let me know - I'd be happy to put a little work in.

As for the casts between the Vector structs, I apparently had an old version from the main site. Everything works as expected after using libraries compiled from the source here. Will I need to update the csfml libraries to avoid causing trouble?

**Comment by zsbzsb** [comment]
>If you guys are interested in conversion between the Vector structs and the built-in equivalents (Point, Size, etc.)

Well first we need to decide if we want it and those type of discussions should happen on the forum (in the SFML.NET subforum). After all, implementation of something trivial like this doesn't require much work.

As for the other mentioned things... I already [answered](http://en.sfml-dev.org/forums/index.php?topic=17670.msg127071#msg127071) you on the forums, so no need to repeat myself.

**Comment by eizengan** [comment]
Understood, and thanks for the help! I'll close this issue and start a post on the subforum.
