### ISSUE TITLE
SoundRecorder.DefaultDevice crashes program when used

### ISSUE THREAD

**Issue by eizengan** [LaurentGomila/SFML.Net#108]
Any attempts to use SoundRecorder.DefaultDevice (even as a watch while debugging) instantly crash the simple console program I'm working on. SoundRecorder.IsAvailable returns true, and I can use the strings in SoundRecorder.AvailableDevices without crashing the program. Output after the crash doesn't provide anything useful, but I'd be willing to compile a debug version of the SFML.NET libraries and post more info if no one can replicate this.

Currently using the most recent 64-bit release of SFML.NET in VS Express 2013 on a computer running Win7.

**Comment by zsbzsb** [comment]
Fixed in #109

**Comment by eizengan** [comment]
Awesome! What's SOP here? Close this request since this is covered elsewhere?

**Comment by zsbzsb** [comment]
It really doesn't matter if this is closed now or later, the fix should be merged once @LaurentGomila reviews it.

**Comment by eizengan** [comment]
Better now, as I tend to be pretty forgetful. Thanks zsbzsb.
