### ISSUE TITLE
Remove extlibs folder

### ISSUE THREAD

**Issue by zsbzsb** [LaurentGomila/SFML.Net#91]
Considering all the changes that are constantly happening it is difficult to keep the extlibs up to date. I think in order to keep this more consistent with the CSFML project we should remove the extlibs folder and allow users to get CSFML themselves. This would increase cross platform support as we won't need to provide builds in the actual repository for every single platform (which we don't already).

It would also remove confusion when people download the updated SFML.NET repository and then it doesn't work with the provided extlibs. It would be simpler to mention in the readme that you must get CSFML (either by compiling or downloading a CSFML release) in order to use SFML.NET.

Of course this wouldn't affect packaged releases as we would still include compiled SFML/CSFML in those packages.

**Comment by LaurentGomila** [comment]
Sounds reasonable.

What would it involve to have the CSFML files anywhere? Would it change something to the project files and/or code?

**Comment by zsbzsb** [comment]
I am only talking about removing the precompiled dependencies. The CSFML project does not contain anything precompiled from SFML. So I was suggesting for SFML.NET to remain consistent that we would also remove the precompiled dependencies (extlibs folder).

This wouldn't affect any of the existing project files or code.

**Comment by LaurentGomila** [comment]
I got your point, your last sentence was all I needed :p

So we will still be able to compile SFML.Net, and we would only need to copy the CSFML binaries (somewhere in the PATH or next to the SFML.Net executable) to make it work?

**Comment by zsbzsb** [comment]
To compile SFML.NET you don't even need the extlibs - you only need it when running the executable.

>only need to copy the CSFML binaries (somewhere in the PATH or next to the SFML.Net executable) to make it work?

Yes, this has always been the case.

**Comment by LaurentGomila** [comment]
Ok so let's do it.
