### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by zsbzsb** [LaurentGomila/SFML.Net#93]
Todo list before we can release 2.2. CSFML now has the required changes so all that is required now is to now implement them in SFML.NET.

-=SFML.NET=-

~~window focus has/request~~ #94
~~underline position/thickness~~ #95
~~font info~~ #96
~~joystick info~~ #97
~~sound recorder start/bool return~~ #99
~~sound recorder devices~~ #99
~~sensor api~~ #102
~~touch api~~ #102
~~sensor and touch events~~ #102
color int constructor https://github.com/LaurentGomila/SFML/pull/722 - **after 2.2**

**Comment by zsbzsb** [comment]
I'm guessing you want the sensor/touch API implemented here too :S

**Comment by LaurentGomila** [comment]
Of course :p

**Comment by zsbzsb** [comment]
And the checklist for 2.2 is cleared for here also... So I will make a PR to update version numbers to 2.2 and you can merge in a few days.

**Comment by LaurentGomila** [comment]
Great :+1:

**Comment by zsbzsb** [comment]
#103 is good to go!

**Comment by zsbzsb** [comment]
And since this is complete... time to close :smile:
